Invoice/InvoiceUnach/Invoice.Admin/Controllers/SubsidiaryController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Invoice.Admin.Models;
using Invoice.Domain.Interfaces.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Invoice.Admin.Controllers
{
    public class SubsidiaryController : Controller
    {
        private readonly ILogger<SubsidiaryController> _logger;
        private readonly ISubsidiaryRepository _subsidiaryRepository;

        public SubsidiaryController(ILogger<SubsidiaryController> logger, ISubsidiaryRepository subsidiaryRepository)
        {
            _logger = logger;
            _subsidiaryRepository = subsidiaryRepository;
        }
        
        // GET
        public async Task<IActionResult> Index(Guid userId)
        {
            return View(await GetSubsidiaries(userId));
        }

        #region Methods Update

        public async Task<IActionResult> LoadSubsidiary(Guid subsidiaryId)
        {
            var subsidiaryModel = new SubsidiaryModel();

            subsidiaryModel.Option = "Edit";
            
            var subsidiary = await _subsidiaryRepository.GetById(subsidiaryId);
            
            subsidiaryModel.InputSubsidiaryModel= 
                new SubsidiaryModel.InputSubsidiary
                {
                    Id = subsidiary.Id,
                    Name = subsidiary.Name,
                    Address = subsidiary.Address,
                    Phone1 = subsidiary.Phone1,
                    Phone2 = subsidiary.Phone2,
                    UserId = subsidiary.UserId
                };
            
            return View("Index", subsidiaryModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> Update(SubsidiaryModel subsidiaryModel)
        {
            if (ModelState.IsValid)
            {
                var subsidiary = await _subsidiaryRepository.GetById(subsidiaryModel.InputSubsidiaryModel.Id);
                
                subsidiary.SetName(subsidiaryModel.InputSubsidiaryModel.Name);
                subsidiary.SetAddress(subsidiaryModel.InputSubsidiaryModel.Address);
                subsidiary.SetPhone1(subsidiaryModel.InputSubsidiaryModel.Phone1);
                subsidiary.SetPhone2(subsidiaryModel.InputSubsidiaryModel.Phone2);
                
                _subsidiaryRepository.Update(subsidiary);
                await _subsidiaryRepository.UnitOfWork.SaveEntitiesAsync();

                subsidiaryModel = await GetSubsidiaries(subsidiaryModel.InputSubsidiaryModel.UserId);

                return await Task.Run(() => View("Index", subsidiaryModel));
            }
            else
            {
                return await Task.Run(() => View("Index", subsidiaryModel));
            }
        }

        #endregion
        #region Methods Delete

        public async Task<IActionResult> Delete(Guid subsidiaryId, Guid userId)
        {
            var subsidiary = await _subsidiaryRepository.GetById(subsidiaryId);

            _subsidiaryRepository.Delete(subsidiary);
            await _subsidiaryRepository.UnitOfWork.SaveEntitiesAsync();

            var subsidiaryModel = await GetSubsidiaries(userId);

            return View("Index", subsidiaryModel);
        }

        #endregion
       
        
        #region Private Methods
        
        private async Task<SubsidiaryModel> GetSubsidiaries (Guid userId)
        {
            var subsidiaryModel = new SubsidiaryModel();

            subsidiaryModel.Option = "List";
            subsidiaryModel.UserId = userId;

            subsidiaryModel.InputSubsidiaries = new List<SubsidiaryModel.InputSubsidiary>();

            var subsidiaries = await _subsidiaryRepository.Get(userId);

            foreach (var subsidiary in subsidiaries)
            {
                subsidiaryModel.InputSubsidiaries.Add(
                    new SubsidiaryModel.InputSubsidiary
                {
                    Id = subsidiary.Id,
                    Name = subsidiary.Name,
                    Address = subsidiary.Address,
                    Phone1 = subsidiary.Phone1,
                    Phone2 = subsidiary.Phone2,
                    UserId = subsidiary.UserId
                });
            }
            
            return subsidiaryModel;
            
        }
        
        #endregion
        
    }
}

Invoice/InvoiceUnach/Invoice.Admin/Views/Subsidiary/index.cshtml
@model Invoice.Admin.Models.SubsidiaryModel;
@{
    ViewBag.Title = "Facturación | Sucursales";
    Layout = "_Layout";
}
<div class="col-md-12">
    <h1>Sucursales</h1>
</div>
<hr/>
@if (Model.Option == "List")
{
    <div class="col-md-12">
        <div class="card">
            <div class="card-title">
                <h2>Listado de Sucursales</h2>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                    <a class="btn btn-primary btn-sm float-right" asp-action="LoadFormCreate" asp-route-userId="@Model.UserId">Agregar <i class="fa fa-plus"></i></a>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Dirección</th>
                            <th scope="col">Teléfono1</th>
                            <th scope="col">Teléfono2</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach (var subsidiary in @Model.InputSubsidiaries)
                        {
                            <tr>
                                <td>@subsidiary.Name</td>
                                <td>@subsidiary.Address</td>
                                <td>@subsidiary.Phone1</td>
                                <td>@subsidiary.Phone2</td>
                                <td>
                                    <a asp-action="LoadSubsidiary" asp-route-subsidiaryId="@subsidiary.Id" class="btn btn-warning btn-sm text-white">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger btn-sm text-white">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>

                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a class="btn btn-outline-secondary btn-sm" href="../UserDetail/Index?userId=@Model.UserId"><i class="fa fa-angle-left"></i> Volver</a>
            </div>
        </div>
    </div>
}
@if (Model.Option == "Edit")
{
    <div class="col-md-12">
        <form method="post" asp-controller="Subsidiary" asp-action="Update">
            <div class="card">
                <div class="card-title">
                    <h2>Editar</h2>
                </div>
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="@Model.InputSubsidiaryModel.Id"/>
                    @Html.HiddenFor(model => model.Option)
                    <div class="row">
                        <div class="col">
                            <input asp-for="InputSubsidiaryModel.Name" class="form-control" placeholder="Nombre">
                            <span asp-validation-for="InputSubsidiaryModel.Name" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <input asp-for="InputSubsidiaryModel.Address" class="form-control" placeholder="Dirección">
                            <span asp-validation-for="InputSubsidiaryModel.Address" class="text-danger"></span>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col">
                            <input asp-for="InputSubsidiaryModel.Phone1" class="form-control" placeholder="Teléfono1">
                            <span asp-validation-for="InputSubsidiaryModel.Phone1" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <input asp-for="InputSubsidiaryModel.Phone2" class="form-control" placeholder="Teléfono2">
                            <span asp-validation-for="InputSubsidiaryModel.Phone2" class="text-danger"></span>
                        </div>
                    </div>
                    <br/>
                </div>
                <div class="card-footer">
                    <a class="btn btn-outline-secondary btn-sm"><i class="fa fa-angle-left"></i> Volver</a>
                    <button class="btn btn-outline-success btn-sm" type="submit">Actualizar <i class="fa fa-save"></i></button>
                </div>
            </div>
        </form>
    </div>
}
@if (Model.Option == "Add")
{
    <div class="col-md-12">
        <form method="post" asp-controller="Subsidiary" asp-action="Create">
            <div class="card">
                <div class="card-title">
                    <div class="col-md-12">
                        <h2>Nuevo</h2>
                    </div>
                </div>
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @Html.HiddenFor(model => model.Option)
                    @Html.HiddenFor(model => model.UserId)
                    <div class="row">
                        <div class="col">
                            <label>Nombre:</label>
                            <input asp-for="InputSubsidiaryModel.Name" class="form-control" placeholder="Nombre">
                            <span asp-validation-for="InputSubsidiaryModel.Name" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <label>Dirección:</label>
                            <input asp-for="InputSubsidiaryModel.Address" class="form-control" placeholder="Dirección">
                            <span asp-validation-for="InputSubsidiaryModel.Address" class="text-danger"></span>
                        </div>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col">
                            <label>Teléfono1:</label>
                            <input asp-for="InputSubsidiaryModel.Phone1" class="form-control" placeholder="Teléfono1">
                            <span asp-validation-for="InputSubsidiaryModel.Phone1" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <label>Teléfono2:</label>
                            <input asp-for="InputSubsidiaryModel.Phone2" class="form-control" placeholder="Teléfono2">
                            <span asp-validation-for="InputSubsidiaryModel.Phone2" class="text-danger"></span>
                        </div>
                    </div>
                    <br/>
                </div>
                <div class="card-footer">
                    <a class="btn btn-outline-secondary btn-sm" href="../Subsidiary/Index?userId=@Model.UserId"><i class="fa fa-angle-left"></i> Volver</a>
                    <button class="btn btn-outline-success btn-sm" type="submit">Guardar <i class="fa fa-save"></i></button>
                </div>
            </div>
        </form>
    </div>
}